appName: currencyservice
appImage: gcr.io/google-samples/microservices-demo/currencyservice
appVersion: v0.4.1
appReplicas: 2
containerPort: 7000
containerEnvVars:
- name: PORT
  value: "7000"
- name: ENABLE_TRACING
  value: "false"
- name: ENABLE_DEBUGGER
  value: "false"
- name: GOOGLE_CLOUD_PROFILER
  value: "false"
- name: GOOGLE_APPLICATION_CREDENTIALS
  value: ""
- name: DISABLE_PROFILER
  value: "true"
- name: OTEL_SERVICE_NAME
  value: "currencyservice"
- name: COLLECTOR_SERVICE_ADDR
  value: ""

servicePort: 7000